trigger:
  branches:
    include:
    - release/*

pr: none

jobs:
  - job: 'Build'
    
    strategy:
      maxParallel: 5
      matrix:
        linux_node-8.x:
          imageName: 'ubuntu-16.04'
          node_version: 8.x
        linux_node-10.x:
          imageName: 'ubuntu-16.04'
          node_version: 10.x
        linux_node-12.x:
          imageName: 'ubuntu-16.04'
          node_version: 12.x
        windows_node-12.x:
          imageName: 'vs2017-win2016'
          node_version: 12.x
        macOS_node-12.x:
          imageName: 'macos-10.13'
          node_version: 12.x
    
    pool:      
      vmImage: $(imageName)
      
    steps:
      - task: NodeTool@0
        displayName: 'Use node $(node_version)'
        inputs:
          versionSpec: $(node_version)
      
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          command: install
          verbose: false

      - task: Npm@1
        displayName: 'Compile TypeScript'
        inputs:
          command: custom
          customCommand: 'run compile'
          verbose: false

      - task: Bash@3
        displayName: 'Start xvfb if running Linux'
        condition: eq(variables['Agent.OS'], 'Linux')
        inputs:
          targetType: 'inline'
          script: |
            set -e
            /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
            disown -ar

      - task: Npm@1
        displayName: 'Run Tests'
        env:
          DISPLAY: :10
        inputs:
          command: custom
          customCommand: 'run test'
          verbose: false

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: '$(Agent.OS) (node: $(node_version))'
          
  - job: 'Publish'
    displayName: 'Publish VSIX Package'
    dependsOn: 'Build'
    condition: succeeded()

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: NodeTool@0
        displayName: 'Use node 12.x'
        inputs:
          versionSpec: 12.x
      
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          command: install
          verbose: false
      
      - task: Npm@1
        displayName: 'Create VSIX package'
        inputs:
          command: custom
          customCommand: 'run package'
          verbose: false

      - task: PublishPipelineArtifact@1
        displayName: 'Publish pipeline artifact'
        inputs:
          targetPath: 'release.vsix'
