trigger: none

jobs:
  - job: 'Build'
    
    strategy:
      maxParallel: 3
      matrix:
        linux_node-12.4:
          imageName: 'ubuntu-16.04'
          node_version: 12.4
        windows_node-12.4:
          imageName: 'vs2017-win2016'
          node_version: 12.4
        macOS_node-12.4:
          imageName: 'macos-10.13'
          node_version: 12.4

    pool:
      vmImage: $(imageName)

    steps:
      - task: NodeTool@0
        displayName: 'Use node $(node_version)'
        inputs:
          versionSpec: $(node_version)
      
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          command: install
          verbose: false

      - task: Npm@1
        displayName: 'Compile TypeScript'
        inputs:
          command: custom
          customCommand: 'run compile'
          verbose: false

      - task: Bash@3
        displayName: 'Start xvfb if running Linux'
        condition: eq(variables['Agent.OS'], 'Linux')
        inputs:
          targetType: 'inline'
          script: |
            set -e
            /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
            disown -ar

      - task: Npm@1
        displayName: 'Run Tests'
        env:
          DISPLAY: :10
        inputs:
          command: custom
          customCommand: 'run test'
          verbose: false